// Manual-check harness for /coms-setup (ticket 06).
//
// Runs the real command handler against fake pi/ctx objects and scratch
// XDG_CONFIG_HOME + PI_CODING_AGENT_DIR dirs, so nothing on the real machine
// is touched. Usage:
//
//   node tests/coms-setup.mjs
//
// Exit code 0 = every case passed.

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";
import { runComsSetup } from "../extensions/coms-setup.ts";

const REPO = path.resolve(import.meta.dirname, "..");
const ROOT = fs.mkdtempSync(path.join(os.tmpdir(), "coms-setup-check-"));

let passed = 0;
const failures = [];

function report(name, ok, detail = "") {
  if (ok) {
    passed++;
    console.log(`  ok   ${name}`);
  } else {
    failures.push(name);
    console.log(`  FAIL ${name}${detail ? ` :: ${detail}` : ""}`);
  }
}

function check(name, cond, detail = "") {
  report(name, !!cond, detail);
}

function include(name, text, needle) {
  report(name, text.includes(needle), `missing ${JSON.stringify(needle)} in:\n${text}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────

let seq = 0;
function scratch(name) {
  const dir = path.join(ROOT, `${String(++seq).padStart(2, "0")}-${name}`);
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function makePackage(name) {
  const dir = path.join(ROOT, `${String(++seq).padStart(2, "0")}-${name}`);
  fs.mkdirSync(path.join(dir, "extensions"), { recursive: true });
  fs.copyFileSync(path.join(REPO, "justfile"), path.join(dir, "justfile"));
  fs.cpSync(path.join(REPO, "roles"), path.join(dir, "roles"), { recursive: true });
  fs.cpSync(path.join(REPO, "scripts"), path.join(dir, "scripts"), { recursive: true });
  fs.writeFileSync(path.join(dir, "extensions", "coms.ts"), "// fake entry\n");
  return dir;
}

function fakePi(pkgRoot, entry = {}) {
  const entryPath = path.join(pkgRoot, "extensions", "coms.ts");
  return {
    getCommands: () => [
      {
        name: "coms",
        description: "",
        source: "extension",
        sourceInfo: {
          path: entryPath,
          source: entry.source ?? pkgRoot,
          scope: entry.scope ?? "user",
          origin: entry.origin ?? "package",
          ...(entry.baseDir ? { baseDir: entry.baseDir } : {}),
        },
      },
    ],
  };
}

function fakeCtx(opts = {}) {
  const messages = [];
  const ctx = {
    hasUI: opts.hasUI ?? false,
    cwd: opts.cwd ?? ROOT,
    ui: {
      notify: (text, kind = "info") => messages.push({ text, kind }),
      confirm: async (title, message) => {
        messages.push({ text: `[dialog] ${title} :: ${message}`, kind: "dialog" });
        return opts.confirm ? opts.confirm() : false;
      },
    },
  };
  return { ctx, messages };
}

async function withEnv(env, fn) {
  const saved = { ...process.env };
  for (const key of Object.keys(process.env)) delete process.env[key];
  Object.assign(process.env, saved, env);
  try {
    return await fn();
  } finally {
    for (const key of Object.keys(process.env)) delete process.env[key];
    Object.assign(process.env, saved);
  }
}

async function run(pkgRoot, opts = {}) {
  const { ctx, messages } = fakeCtx(opts);
  await withEnv(
    {
      XDG_CONFIG_HOME: opts.xdg,
      PI_CODING_AGENT_DIR: opts.agentDir ?? scratch("agent"),
      ...(opts.env ?? {}),
    },
    () =>
      runComsSetup(
        fakePi(pkgRoot, opts.entry ?? {}),
        opts.args ?? "",
        ctx,
        pathToFileURL(path.join(pkgRoot, "extensions", "coms.ts")).href,
      ),
  );
  return {
    out: messages.map((m) => m.text).join("\n"),
    messages,
    last: messages[messages.length - 1],
  };
}

function execJust(args, xdg) {
  return spawnSync("just", args, {
    encoding: "utf8",
    env: { ...process.env, XDG_CONFIG_HOME: xdg },
  });
}

function markerV1(pkgRoot) {
  return [
    "# Managed by pi-ext-agent-comms. Generated by /coms-setup; do not edit.",
    "# coms-setup-shim v1",
    `import ${JSON.stringify(path.join(pkgRoot, "justfile"))}`,
    "",
  ].join("\n");
}

// ── cases ───────────────────────────────────────────────────────────────────

async function freshShim() {
  console.log("\nfresh shim (scratch XDG, no just/ dir yet)");
  const pkg = makePackage("pkg-a");
  const xdg = scratch("xdg-a");
  const res = await run(pkg, { xdg });
  const shim = path.join(xdg, "just", "justfile");

  include("reports the wiring", res.out, `wired ${shim} -> ${pkg}  (coms-setup-shim v1)`);
  include("reports the install identity", res.out, `loaded as a package install (${pkg}, scope user)`);
  include("reports just version", res.out, "just 1.58.0");
  include("warns about dev deps", res.out, "just typecheck: dev deps missing");
  include("tells the user what to run", res.out, "run: just -g --list");
  check("info kind", res.last?.kind === "info", res.last?.kind);
  check("shim bytes are the literal text", fs.readFileSync(shim, "utf8") === markerV1(pkg));

  const settings = path.join(xdg, "just", "coms.env");
  include("reports the settings file", res.out, `settings: created ${settings}`);
  check("settings file written", fs.existsSync(settings), settings);
  if (fs.existsSync(settings)) {
    const text = fs.readFileSync(settings, "utf8");
    include("settings template names PI_COMS_TEAM", text, "#PI_COMS_TEAM=team");
    include("settings template explains the precedence", text, "environment variable always");
    check("settings mode 0644", (fs.statSync(settings).mode & 0o777) === 0o644);
  }

  const list = execJust(["-g", "--list"], xdg);
  check("just -g --list works", list.status === 0, list.stderr);
  const evalRes = execJust(["-g", "--no-dotenv", "--evaluate", "repo"], xdg);
  check("just -g --evaluate repo == package", evalRes.stdout === pkg, JSON.stringify(evalRes.stdout));
  const modes = fs.statSync(shim).mode & 0o777;
  check("shim mode 0644", modes === 0o644, modes.toString(8));
}

async function idempotent() {
  console.log("\nrerun is idempotent");
  const pkg = makePackage("pkg-idem");
  const xdg = scratch("xdg-idem");
  await run(pkg, { xdg });
  const shim = path.join(xdg, "just", "justfile");
  const before = fs.readFileSync(shim, "utf8");
  const settings = path.join(xdg, "just", "coms.env");
  fs.writeFileSync(settings, "PI_COMS_TEAM=mine\n");
  const res = await run(pkg, { xdg });
  check("rewrites byte-identical", fs.readFileSync(shim, "utf8") === before);
  check("never overwrites settings", fs.readFileSync(settings, "utf8") === "PI_COMS_TEAM=mine\n");
  include("reports the existing settings file", res.out, `settings: ${settings}`);
  check("no settings-created note", !res.out.includes("settings: created"));
  check("no repoint note", !res.out.includes("repointed"));
  check("no upgrade note", !res.out.includes("upgraded"));
  check("still success", res.out.includes("wired"));
}

async function movedPackage() {
  console.log("\npackage moved (local checkout -> other checkout)");
  const a = makePackage("pkg-move-a");
  const b = makePackage("pkg-move-b");
  const xdg = scratch("xdg-move");
  await run(a, { xdg });
  const res = await run(b, { xdg });
  const shim = fs.readFileSync(path.join(xdg, "just", "justfile"), "utf8");
  check("shim points at the new root", shim.includes(JSON.stringify(path.join(b, "justfile"))));
  include("reports the repoint", res.out, `repointed the shim from ${a} to ${b}`);
  const evalRes = execJust(["-g", "--no-dotenv", "--evaluate", "repo"], xdg);
  check("verify resolves the new root", evalRes.stdout === b, evalRes.stdout);
}

async function markerVersions() {
  console.log("\nshim marker versions");
  const pkg = makePackage("pkg-marker");
  const xdg = scratch("xdg-marker");
  const shim = path.join(xdg, "just", "justfile");
  fs.mkdirSync(path.dirname(shim), { recursive: true });

  fs.writeFileSync(shim, "# coms-setup-shim v2\nimport \"/old/justfile\"\n");
  const newer = await run(pkg, { xdg });
  include("refuses a newer marker", newer.out, "newer coms-setup");
  check("left the newer shim alone", fs.readFileSync(shim, "utf8").includes("v2"));

  fs.writeFileSync(shim, `# coms-setup-shim v0\nimport ${JSON.stringify("/old/justfile")}\n`);
  const older = await run(pkg, { xdg });
  include("upgrades an older marker", older.out, "upgraded the shim from v0 to v1");
  check("marker is v1 now", fs.readFileSync(shim, "utf8").includes("# coms-setup-shim v1"));
}

async function foreignFile() {
  console.log("\nforeign regular justfile");
  const pkg = makePackage("pkg-foreign");
  const xdg = scratch("xdg-foreign");
  const shim = path.join(xdg, "just", "justfile");
  fs.mkdirSync(path.dirname(shim), { recursive: true });
  const foreign = "# my own justfile\nhi:\n    echo hi\n";
  fs.writeFileSync(shim, foreign);

  const refused = await run(pkg, { xdg });
  include("refuses without force", refused.out, "did not write");
  include("names the force backup path", refused.out, `justfile.bak-`);
  check("file untouched", fs.readFileSync(shim, "utf8") === foreign);
  check("error kind", refused.last?.kind === "error", refused.last?.kind);

  const forced = await run(pkg, { xdg, args: "force" });
  include("force succeeds", forced.out, "wired");
  const backups = fs.readdirSync(path.join(xdg, "just")).filter((f) => f.startsWith("justfile.bak-"));
  check("one backup written", backups.length === 1, JSON.stringify(backups));
  check(
    "backup holds the old file",
    backups.length === 1 && fs.readFileSync(path.join(xdg, "just", backups[0]), "utf8") === foreign,
  );
  check("shim now ours", fs.readFileSync(shim, "utf8").startsWith("# Managed by pi-ext-agent-comms."));
}

async function symlink() {
  console.log("\nsymlinked justfile (the user's current setup)");
  const pkg = makePackage("pkg-link");
  const xdg = scratch("xdg-link");
  const justDir = path.join(xdg, "just");
  fs.mkdirSync(justDir, { recursive: true });
  const target = path.join(ROOT, "linked-justfile-target");
  const targetBody = "# the real file this link points at\n";
  fs.writeFileSync(target, targetBody);
  const shim = path.join(justDir, "justfile");
  fs.symlinkSync(target, shim);

  const refused = await run(pkg, { xdg });
  include("refuses the symlink", refused.out, "symlink");
  include("tells the user not to write through it", refused.out, "rewrite the file it points at");
  check("link still a symlink", fs.lstatSync(shim).isSymbolicLink());
  check("target byte-identical", fs.readFileSync(target, "utf8") === targetBody);

  const forced = await run(pkg, { xdg, args: "force" });
  include("force succeeds", forced.out, "wired");
  include("prints the old target", forced.out, target);
  check("link node replaced by a regular file", fs.lstatSync(shim).isFile());
  check("target still byte-identical", fs.readFileSync(target, "utf8") === targetBody);
  check("shim is ours", fs.readFileSync(shim, "utf8").includes("# coms-setup-shim v1"));
}

async function directory() {
  console.log("\ndirectory in the shim's place");
  const pkg = makePackage("pkg-dir");
  const xdg = scratch("xdg-dir");
  const shim = path.join(xdg, "just", "justfile");
  fs.mkdirSync(shim, { recursive: true });
  for (const args of ["", "force"]) {
    const res = await run(pkg, { xdg, args });
    include(`refuses a directory (${args || "default"})`, res.out, "is a directory");
    check(`directory still there (${args || "default"})`, fs.statSync(shim).isDirectory());
  }
}

async function devLoad() {
  console.log("pi -e load (origin top-level)");
  const pkg = makePackage("pkg-deve");
  const xdg = scratch("xdg-deve");
  const res = await run(pkg, { xdg, entry: { origin: "top-level", baseDir: undefined } });
  include("refuses non-package loads", res.out, "-e/--extension");
  include("gives the install recipe", res.out, "pi install git:github.com/macmacs/pi-ext-agent-comms");
  include("mentions the local-path dev install", res.out, "pi install /path/to/checkout");
  check("no shim written", !fs.existsSync(path.join(xdg, "just", "justfile")));
}

async function justProblems() {
  console.log("\njust missing or too old");
  const pkg = makePackage("pkg-just");

  const xdgMissing = scratch("xdg-just-missing");
  const emptyPath = scratch("empty-path");
  const missing = await run(pkg, { xdg: xdgMissing, env: { PATH: emptyPath } });
  include("refuses a missing just", missing.out, "not found on PATH");
  check("no shim written", !fs.existsSync(path.join(xdgMissing, "just", "justfile")));

  const xdgOld = scratch("xdg-just-old");
  const fakeBin = scratch("fake-bin");
  fs.writeFileSync(path.join(fakeBin, "just"), "#!/bin/sh\necho 'just 1.30.0'\n");
  fs.chmodSync(path.join(fakeBin, "just"), 0o755);
  const old = await run(pkg, {
    xdg: xdgOld,
    env: { PATH: `${fakeBin}${path.delimiter}${process.env.PATH}` },
  });
  include("refuses an old just", old.out, "too old");
  include("prints installed vs required", old.out, "1.30.0");
  check("no shim written", !fs.existsSync(path.join(xdgOld, "just", "justfile")));
}

async function typecheckReady() {
  console.log("\nlocal typescript present");
  const pkg = makePackage("pkg-tsc");
  const tscDir = path.join(pkg, "node_modules", "typescript", "bin");
  fs.mkdirSync(tscDir, { recursive: true });
  fs.writeFileSync(path.join(tscDir, "tsc"), "#!/usr/bin/env node\n");
  const res = await run(pkg, { xdg: scratch("xdg-tsc") });
  include("reports typecheck ready", res.out, "just typecheck: ready");
}

async function incompletePackage() {
  console.log("\nincomplete package");
  const pkg = makePackage("pkg-incomplete");
  fs.rmSync(path.join(pkg, "roles"), { recursive: true, force: true });
  const res = await run(pkg, { xdg: scratch("xdg-incomplete") });
  include("refuses an incomplete package", res.out, "incomplete package");
  include("names the missing entry", res.out, "roles");
}

async function baseDirMismatch() {
  console.log("\nbaseDir mismatch (loader disagrees with the extension path)");
  const pkg = makePackage("pkg-basedir");
  const res = await run(pkg, { xdg: scratch("xdg-basedir"), entry: { baseDir: "/somewhere/else" } });
  include("warns but proceeds", res.out, "note: the loader reports baseDir /somewhere/else");
  check("still wired", res.out.includes("wired"));
}

async function override() {
  console.log("\nPI_COMS_REPO override");
  const pkg = makePackage("pkg-override");
  const other = scratch("override-repo");
  const res = await run(pkg, { xdg: scratch("xdg-override"), env: { PI_COMS_REPO: other } });
  include("reports the override", res.out, `PI_COMS_REPO=${other} override is in effect`);
  include("still wired", res.out, "wired");
}

async function settingsCleanup() {
  console.log("\nstale settings filter");
  const pkg = makePackage("pkg-settings");
  const makeSettings = (dir) => {
    fs.mkdirSync(dir, { recursive: true });
    const file = path.join(dir, "settings.json");
    fs.writeFileSync(
      file,
      JSON.stringify(
        {
          lastChangelogVersion: "0.0.0",
          packages: [
            "npm:something-else",
            { source: pkg, extensions: ["extensions/*.ts", "!extensions/coms-net.ts"] },
          ],
        },
        null,
        2,
      ) + "\n",
    );
    return file;
  };
  const listed = JSON.stringify(["extensions/*.ts", "!extensions/coms-net.ts"]);

  // No dialog: report only, never write.
  const agentA = scratch("agent-report");
  const fileA = makeSettings(agentA);
  const beforeA = fs.readFileSync(fileA, "utf8");
  const reportOnly = await run(pkg, { xdg: scratch("xdg-report"), agentDir: agentA, hasUI: false });
  include("reports the stale filter", reportOnly.out, "still carries a stale extensions filter");
  include("names the exact edit", reportOnly.out, listed);
  check("settings untouched without a dialog", fs.readFileSync(fileA, "utf8") === beforeA);

  // Dialog declined: same.
  const agentB = scratch("agent-decline");
  const fileB = makeSettings(agentB);
  const beforeB = fs.readFileSync(fileB, "utf8");
  const declined = await run(pkg, {
    xdg: scratch("xdg-decline"),
    agentDir: agentB,
    hasUI: true,
    confirm: () => false,
  });
  include("reports when declined", declined.out, "still carries a stale extensions filter");
  check("settings untouched when declined", fs.readFileSync(fileB, "utf8") === beforeB);

  // Dialog accepted: backup + clean.
  const agentC = scratch("agent-clean");
  const fileC = makeSettings(agentC);
  const cleaned = await run(pkg, {
    xdg: scratch("xdg-clean"),
    agentDir: agentC,
    hasUI: true,
    confirm: () => true,
  });
  include("reports the cleanup", cleaned.out, `cleaned the stale extensions filter in ${fileC}`);
  const after = JSON.parse(fs.readFileSync(fileC, "utf8"));
  check("entry is a plain string now", after.packages[1] === pkg, JSON.stringify(after.packages[1]));
  check("other entry untouched", after.packages[0] === "npm:something-else");
  check("other settings kept", after.lastChangelogVersion === "0.0.0");
  const backups = fs.readdirSync(agentC).filter((f) => f.startsWith("settings.json.bak-"));
  check("settings backup written", backups.length === 1, JSON.stringify(backups));
  report(
    "dialog asked for confirmation",
    cleaned.messages.some((m) => m.kind === "dialog" && m.text.includes("Clean stale coms filter?")),
  );

  // A plain-string entry has nothing to clean.
  const agentD = scratch("agent-plain");
  fs.mkdirSync(agentD, { recursive: true });
  const fileD = path.join(agentD, "settings.json");
  fs.writeFileSync(fileD, JSON.stringify({ packages: [pkg] }, null, 2) + "\n");
  const plain = await run(pkg, { xdg: scratch("xdg-plain"), agentDir: agentD, hasUI: false });
  check("no filter line for a plain entry", !plain.out.includes("extensions filter"));
}

// ── run ─────────────────────────────────────────────────────────────────────

const cases = [
  freshShim,
  idempotent,
  movedPackage,
  markerVersions,
  foreignFile,
  symlink,
  directory,
  devLoad,
  justProblems,
  typecheckReady,
  incompletePackage,
  baseDirMismatch,
  override,
  settingsCleanup,
];

console.log(`/coms-setup checks (fixtures in ${ROOT})`);
for (const c of cases) {
  try {
    await c();
  } catch (err) {
    failures.push(c.name);
    console.log(`  FAIL ${c.name} threw: ${err?.stack ?? err}`);
  }
}

console.log(`\n${passed} checks passed, ${failures.length} failed`);
if (failures.length > 0) {
  console.log(`failures:\n  ${failures.join("\n  ")}`);
  process.exit(1);
}
